### ISSUE TITLE
tracking issue: Fix directory/file specific layer configuration

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14653]
As reported in https://github.com/syl20bnr/spacemacs/pull/14652, there's a regression since https://github.com/syl20bnr/spacemacs/pull/14509.

> This is a regression we have in multiple languages. We need to add the backend setup function to <major-mode>-local-vars-hook so that people can override a language backend in a given project. See the Emacs documentation on this wonderfully named variable hack-local-variables.
>
> For instance with the following .dir-locals.el at the root of a git repository I can choose to use anaconda instead of lsp (useful for legacy python projects):
>
> ;;; Directory Local Variables
> ;;; For more information see (info "(emacs) Directory Variables")
>
> ((python-mode . ((python-test-runner . pytest)
>                  (python-backend . anaconda))))
>
>This feature is explained in the README.org files of all the languages supporting multiple backends. Example in the Python README: https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/python#choosing-a-backend

 <summary>Review progress</summary>

  - [ ] haskell https://github.com/syl20bnr/spacemacs/pull/14668
  - [ ] c-c++ https://github.com/syl20bnr/spacemacs/pull/14654
  - [ ] clojure https://github.com/syl20bnr/spacemacs/pull/14655
  - [ ] crystal https://github.com/syl20bnr/spacemacs/pull/14656
  - [ ] csharp https://github.com/syl20bnr/spacemacs/pull/14657
  - [x] dart https://github.com/syl20bnr/spacemacs/pull/14658
  - [x] elixir https://github.com/syl20bnr/spacemacs/pull/14659
  - [ ] elm https://github.com/syl20bnr/spacemacs/pull/14661
  - [x] erlang https://github.com/syl20bnr/spacemacs/pull/14662
  - [ ] ess https://github.com/syl20bnr/spacemacs/pull/14663
  - [ ] fsharp https://github.com/syl20bnr/spacemacs/pull/14664
  - [x] go https://github.com/syl20bnr/spacemacs/pull/14665
  - [ ] python https://github.com/syl20bnr/spacemacs/pull/14652
  - [x] groovy https://github.com/syl20bnr/spacemacs/pull/14666
  - [ ] javascript https://github.com/syl20bnr/spacemacs/pull/14670
  - [ ] typescript
  - [ ] java https://github.com/syl20bnr/spacemacs/pull/14669
  - [ ] json https://github.com/syl20bnr/spacemacs/pull/14671
  - [ ] julia https://github.com/syl20bnr/spacemacs/pull/14672
  - [ ] kotlin https://github.com/syl20bnr/spacemacs/pull/14673
  - [ ] latex https://github.com/syl20bnr/spacemacs/pull/14674
  - [ ] lua https://github.com/syl20bnr/spacemacs/pull/14675
  - [ ] nim https://github.com/syl20bnr/spacemacs/pull/14676
  - [ ] perl5 https://github.com/syl20bnr/spacemacs/pull/14677
  - [ ] php
  - [ ] purescript
  - [ ] ruby
  - [ ] rust
  - [ ] scala
  - [ ] shell-scripts
  - [ ] sql
  - [ ] vimscript
  - [ ] spacemacs-defaults
  - [ ] dash
  - [ ] colors
  - [ ] cmake
  - [ ] dap
  - [ ] docker
  - [ ] eaf
  - [ ] terraform
  - [ ] vinegar

Not affected:
- rcirc
- spacemacs-bootstrap
- react
- vue
- xkcd
- chinese
- keyboard-layout
- spacemacs-editing

**Comment by smile13241324** [comment]
Good catch I will check the commits and merge them one by one.

**Comment by syl20bnr** [comment]
Taking care of Ruby.
