### ISSUE TITLE
Tracking issue for copyright compliiance

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14722]
This is a tracking issue regarding a review of copyright compliance in our code base.

- We've recently improved GPL compliance in https://github.com/syl20bnr/spacemacs/pull/14552 after receiving request in https://github.com/syl20bnr/spacemacs/issues/14444.
- This tracking issue differs from the previous one in a few aspects:
  - This not only covers the ELISP scripts in our code base, but also other works, including documentations and images.
  - In addition to existing works currently in our code base, it also include guidelines for future works, specifically, a specific topic in contributing guidelines about copyright compliance.

The non-exhaustive list of things to-do:
- Review all existing works about their copyright compliance.
  - Make sure each and every text document, including but not limited to ELISP files and ORG documents, have update to date license header. Specifically, explicitly declare whether a file IS or IS NOT a part of GNU Emacs.
  - Whenever possible, explicitly mention the author or source of 3rd-party works, in the layer README.org.
  - Add copyright information of images or other non-text documents in documentations.
- Convey the new requirements of copyright compliance in contributing guidelines:
  - If the work to be incorporated to our code base only contain original work, it's perfectly fine and we've nothing more need to do.
  - If it contains works from any 3rd-party, the contributor must
    - Explicitly provide the license of the 3rd-party work, and it must be compatible to our GPL-3 license
    - Proves that the 3rd-party work is in public domain. For example, the author explicitly declared that or the work is too simple/trivial to meet the threshold of copyright protection.
    - Proves that the author has given explicit permission to use the code in our code base.

**Comment by bryce-carson** [comment]
- [ ] Include copyright compliance guidelines in [`CONTRIBUTING.org`](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org)
- [ ] Include copyright notice for R logo in the [ESS layer `README.org`](https://github.com/syl20bnr/spacemacs/blob/18ad9759b29a56ba92fe452b62dd545329175b63/layers/+lang/ess/README.org)
	- [ ] Change R logo in the [ESS layer `README.org`](https://github.com/syl20bnr/spacemacs/blob/18ad9759b29a56ba92fe452b62dd545329175b63/layers/+lang/ess/README.org) to the preferred SVG

---

I am looking at style guides from Red Hat, IBM, and SUSE. These can be helpful, and I'd like to establish a style guide for documentation in Spacemacs as well. That will be tracked below, if I go forward with experimenting with that.

- [ ] Develop a documentation style guide
