### ISSUE TITLE
Checklist of Issues with shell-pop

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1710]
Ok so I found some things wrong with shell-pop that would be cool to resolve
before the release.

- [x] Change to #number shell does not work while having a terminal opened.

[![alt](http://i.imgur.com/ouuNpX2.gif)](http://i.imgur.com/ouuNpX2.gif)

- [x] Exiting ansi-term closes buffer but exiting eshell does not
[![alt](http://i.imgur.com/nnH0nsl.gif)](http://i.imgur.com/nnH0nsl.gif)

- [x] Exiting on a full screen term does not let us close only window, therefore gives warning at exit, and hangs a little.

[![alt](http://i.imgur.com/rw4uovE.gif)](http://i.imgur.com/rw4uovE.gif)

**Comment by tuhdo** [comment]
The first issue is fixed upstream: https://github.com/kyagi/shell-pop-el/issues/23#issuecomment-106661256

**Comment by CestDiego** [comment]
ok I crossed it

**Comment by tuhdo** [comment]
The third one was fixed upstream,

**Comment by tuhdo** [comment]
The second one was fixed upstream with this commit: https://github.com/kyagi/shell-pop-el/pull/28

All of these issues are fixed upstream. You can close this issue.

**Comment by CestDiego** [comment]
ok. but the third one still persists

**Comment by tuhdo** [comment]
> Either exiting term with C-c C-d or with exit kills the process, but doesn't kill the buffer and returns to the last buffer.

What is your default shell? I'm pretty sure it does not happen with `eshell`.

**Comment by CestDiego** [comment]
yes, it doesn't happen with eshell, but it does with ansi-term

**Comment by tuhdo** [comment]
This issue was fixed upstream. You can try again now.

**Comment by CestDiego** [comment]
I can see the fix upstream. This is great, gj tuhdo :)
