### ISSUE TITLE
Update documentation for 0.104

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#2749]
_Note: Some items may be irrelevant, this is a list out of my head._

### DOCUMENTATION.org

- [x] toggles
- [x] powerline segments
- [x] merge LAYERS.org
- [ ] rewrite layer section
- [x] update VIMUSERS.org
- [x] update how to update Spacemacs
- [x] update themes section and screenshots (for new default spacemacs theme)
- [x] new dotdirectory .spacemacs.d
- [x] update guide-key section (now replaced by which-key)
- [x] Names for Prefix Commands #2727 (#2839)
- [ ] Document dotfile reloading with new dotfile tests
- [ ] Document new distribution feature

### Conventions
- [x] ~~Create convention for prefix command names #2839 (#2727)~~

### README.org

- [x] Update how to update Spacemacs
- [x] update guide-key section

**Comment by robbyoconnor** [comment]
#2662 needs to be fixed merged too :)

**Comment by TheBB** [comment]
I can do something for the modeline. You did merge a PR with toggle information... I'm not sure what more is needed.

**Comment by syl20bnr** [comment]
@TheBB it's ok for the toggles, thank you.

**Comment by justbur** [comment]
I took care of the which-key related stuff in #2760

**Comment by justbur** [comment]
.spacemacs.d is in #2761

**Comment by syl20bnr** [comment]
Added #2727

**Comment by syl20bnr** [comment]
Update:

> - [ ] Document dotfile reloading with new dotfile tests
- [ ] Create convention for prefix command names #2839 (#2727)

**Comment by person808** [comment]
#2895 also has some layer documentation updates.

**Comment by person808** [comment]
> update how to update Spacemacs

I believe this is done in `4b2430d`

**Comment by StreakyCobra** [comment]
@syl20bnr Do you still want to keep this issue? Or is it not needed anymore?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
