### ISSUE TITLE
TODO: 24.3 support

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3198]
From #3116

- [x] back port with-evil-after-load
- [ ] make a macro to dispatch advice funcs
- [ ] add a :emacs or something keyword to package list (default is 24.3, only packages needing more recent versions should specify it)
- [ ] display minimum emacs version warnings for both init.el and packages
- [ ] create a 24.3 compatibility layer taking ownership of all :emacs > 24.3 packages and that must be placed at the end of user layer list
- [ ] document a way to get more recent emacs version

**Comment by syl20bnr** [comment]
Aborted, we drop suppport for 24.3 due to the high number of packages requiring an Emacs 24.4 minimum.
