### ISSUE TITLE
spacemacs-ivy: Information and Suggestions

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#4540]
You can now use ivy instead of helm to perform "completions" in spacemacs on the develop branch (e.g., for finding files, searching text, etc.). Note that the support for ivy is far behind helm, because many packages have been incorporated for helm that currently don't have ivy counterparts. There's also no documentation yet for spacemacs and ivy, because this is all very new.

The purpose of this issue is to provide some basic documentation, but also to solicit suggestions. If you find a ivy/counsel function that's a good replacement for something spacemacs did with helm, please suggest it here. Please do not get into arguments about which is better. That's not the point of this. 

As always, PRs are welcome from anyone who can address these things. I don't have time to do this alone. 

## Installation
 1. First update your dotfile by diffing with the template. Also make sure you update to the latest commit of the develop branch.
 2. Replace `spacemacs-helm` in `dotspacemacs-configuration-layers` with `spacemacs-ivy`
 3. Restart and the new packages should be installed automatically. 

## Known issues
 1. spacemacs-layouts has some functions that depend on helm that have not been ported
 2. We may try to support ivy and helm together in the future, but while we build out support for ivy there are no guarantees that you will be able to use both at the same time. 

## TODO
 - [x] Port helm-specific spacemacs-layout functions or at least make them compatible with ivy #4969
 - [x] `SPC ?` #4570
 - [x] Search FAQ with ivy #4671 
 - [x] `spacemacs/search-engine-select` #4672
 - [x] search functions from symbol-highlight micro state  #4919
 - [x] ~~ivy-projectile?~~
   - `helm-projectile` just accumulates multiple sources that are available on other bindings. Since ivy doesn't have good support for multiple sources and all of the sources are already available, I'm not going to make a `ivy-projectile` binding. You can still use `helm-projectile` of course. 

Ref https://github.com/syl20bnr/spacemacs/issues/4528

**UPDATE**: I'm collecting ivy PRs in my ivy branch (#4969). If someone wants to contribute to that branch you can PR against it.

**Comment by AlejandroCatalina** [comment]
I just switched to `spacemacs-ivy` and tried the `ivy-ag` on `SPC /` in .emac.d/.

It searches fine and fast, but when I type more than 3 characters, appears a weird error:
```
error in process sentinel: counsel--async-sentinel: Wrong type argument: arrayp, (("mu*" . t))
error in process sentinel: Wrong type argument: arrayp, (("mu*" . t))
```

I asked for it in gitter and no one seems to have this issue, but i just updated to the last changes in develop and updated packages, so I don't really know what it might be.

Thanks.

**Comment by kostajh** [comment]
In a `todo.org` file containing 3 levels of headings, e.g:

```
* todo.org
** Development
*** Build something
** Project management
*** Something else
```

`SPC s j` only cycles through the 2nd level headings. With `helm`, `SPC s j` allows me to search through the 2nd and 3rd level headings which is much more useful.

**Comment by justbur** [comment]
@kostajh Try changing `org-imenu-depth`

**Comment by kostajh** [comment]
indeed! thanks @justbur. Should this be a default in the org layer?

**Comment by syl20bnr** [comment]
Would be handy to be able to keep the org header faces with `SPC s j` like with helm, I find it more readable.

**Comment by justbur** [comment]
@kostajh sorry, what default are you suggesting?

**Comment by kostajh** [comment]
@justbur `(setq org-imenu-depth 3)` in the `org` layer.

**Comment by justbur** [comment]
@kostajh #4542 I chose 8 to make it consistent with what `helm-org` does.

**Comment by myrjola** [comment]
One gripe I have when enabling ivy is that whenever helm is used for completion the vim-keybindings haven't been set leading to a less than ideal user experience. What would be the best way to handle this transitory period, when ivy support is still being worked on?

For now I enable both `spacemacs-helm` and `spacemacs-ivy` layers for convenience and utiltity. It seems that ivy is enabled last, which changes most of the commands to use ivy and helm is used in cases where there is no ivy equivalent like `helm-descbinds` or in cases when `spacemacs-helm` has shadowed a prefix, like `SPC h SPC`.

**Comment by TheBB** [comment]
> It seems that ivy is enabled last

AFAIK, this depends on the order you list them.

**Comment by syl20bnr** [comment]
The layers are processed in the order of the list but packages are loaded alphabetically so helm comes before ivy. Ivy or helm packages can be forced to load in a pre step with `:step pre`. To do so one can use `dotspacemacs-additional-packages` to add the `:step` keyword to them, the dotfile won't steal ownership (it takes the ownership only if nobody has claimed it).

**Comment by myrjola** [comment]
I think it would be convenient to setup the vim-keybindings to helm even if ivy is loaded by calling `spacemacs//hjkl-completion-navigation` defined in https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/spacemacs-helm/packages.el#L367-L390. The function would have to be moved out from `spacemacs-helm/init-helm`. Is there any simple way to tap into other layer's functions without loading the whole layer? It seems that loading the `spacemacs-helm` layer overrides quite much of ivy functionality, so only changing the bindings should be sufficient.

Maybe I'm approaching this from the wrong way. Should we instead strive to a state where helm will never be used when ivy is enabled?

**Comment by algernon** [comment]
When using `spacemacs-ivy`, and enabling the `search-engines` layer, trying to use it yields the following error:

```
spacemacs/search-engine-select: Symbol's function definition is void: helm
```

**Comment by justbur** [comment]
@algernon Thanks. I'll add that to the list

**Comment by scloudyy** [comment]
I think the code in each layer like

(when (configuration-layer/layer-usedp 'spacemacs-helm)
  (defun python/init-helm-pydoc ()....)

may can be changed to 

(when (configuration-layer/package-usedp 'helm)
  (defun python/init-helm-pydoc ()....)

so if someone use spacemacs-ivy and install helm by himself can also use the packages related to helm just like helm-pydoc.  @justbur

**Comment by justbur** [comment]
@scloudyy @syl20bnr said he didn't want to do this, but it's his call.

**Comment by syl20bnr** [comment]
@scloudyy what enabling both layers then ? Using `package-usedp` is the same as no condition at all, `helm` is always due to the package dependencies.

**Comment by scloudyy** [comment]
The package will be added to "configuration-layer--packages" because of the dependencies? I remember it only add the packages that appear in the used layers or "dotspacemacs-additional-packages"

**Comment by syl20bnr** [comment]
Oh yeah you are right so changing the condition to `package-usedp` won't change anything. ;-)

**Comment by syl20bnr** [comment]
> so if someone use spacemacs-ivy and install helm by himself can also use the packages related to helm just like helm-pydoc.

It will work when adding helm in additional-packages indeed, interesting proposition.
I guess we can change them for `package-usedp` then.

**Comment by justbur** [comment]
Adding helm to additional-packages won't use any of the spacemacs helm configuration. It might get confusing

**Comment by ghoot** [comment]
Nice work @justbur. While testing I played around with a few of the options including fuzzy (via flx) `(setq ivy-re-builders-plist '((t .ivy--regex-fuzzy)))` and `(setq ivy-initial-inputs-alist nil)` which both have their merits and are illustrated here http://oremacs.com/2016/01/06/ivy-flx/. 

Not sure what the preferred approach with spacemacs is re defaults and options, but if nothing else these would be useful to highlight in the layer doc. Noting here for reference.

**Comment by justbur** [comment]
@ghoot I'm not sure I like the fuzzy matching (for a default at least), but I was already removing the initial "^" as I found that annoying.

**Comment by ghoot** [comment]
@justbur yeah. Highlighting it as an option in the docs is prob enough. It's def a taste thing. Not even sure what I prefer myself ...

**Comment by scloudyy** [comment]
@justbur Is there any variable set for ivy to fix the size of the ivy frame just like the " dotspacemacs-helm-resize"? Sometimes the frame is high and sometimes it is low, which makes people feel uncomfortable.

**Comment by justbur** [comment]
@scloudyy As far as I know, no, but try this and if does what you want I'll try to get a variable added to ivy.

```elisp
  (defun set-ivy-window-min-height ()
    (set-window-text-height (selected-window) ivy-height))
  (advice-add 'ivy--minibuffer-setup :before #'set-ivy-window-min-height)
```

**Comment by syl20bnr** [comment]
To add to the list: Ag/Pt results have no occurence highlighting. Not sure if it's high priority but it feels weird.

**Comment by justbur** [comment]
What do you mean by that @syl20bnr

**Comment by abo-abo** [comment]
@justbur

I suggest the following setting in spacemacs-theme/spacemacs-common.el:

    `(ivy-current-match ((,class (:background ,highlight :bold t))))

The reason being that `ivy-minibuffer-match-face-2` etc. use foreground highlighting in this theme, unlike the background highlighting done in the original ivy faces.  Which means that if you assign `:foreground` to `ivy-current-match`, it will overwrite all highlighted foregrounds.

And the following setting for `colir`:

    (setq colir-compose-method 'colir-compose-overlay)

This setting works nicely for dark themes, while the default setting work for light themes.

Here's a screenshot:
![counselmx-spacemacs-theme](https://cloud.githubusercontent.com/assets/2937359/12422948/91b9ae28-bec9-11e5-8003-fbd439aaacae.png)

Each background color is changed in the selection, while the foregrounds remain the same color (but bold).

**Comment by justbur** [comment]
Thank you @abo-abo. Looks good to me. @nashamri do you want to add this to your theme?

**Comment by nashamri** [comment]
@justbur hey there :smile: I've tweaked the theme and this is the result so far:
![d](https://cloud.githubusercontent.com/assets/1207107/12429152/9226fc96-bee0-11e5-8295-e07158926ac3.png)

and the light version:
![l](https://cloud.githubusercontent.com/assets/1207107/12429156/9934aab0-bee0-11e5-9719-5467985adaac.png)

So it's kind of looks good on both versions and as for the variable `colir-compose-method` I believe the behaviour is changed in spacemacs with this commit https://github.com/syl20bnr/spacemacs/commit/9b7789124b0239485db49cfc943be50ab5e95254

**Comment by sooheon** [comment]
Great work so far on this :). One thing I noticed switching from my config was that the smex-enabled recent commands history didn't seem to be taking effect. Any ideas why this is so?

**Comment by justbur** [comment]
@sooheon I can bind `M-x`. I have `counsel-M-x` bound to the spacemacs version of `M-x`, but I can do it for both. 

Anything else you'd like to contribute or change?

**Comment by scloudyy** [comment]
May I ask how to enabled spacemacs-ivy and spacemacs-helm at the same time but use the spacemacs-ivy.To enable spacemacs-helm just don't want to lose the packsges related to helm.
Is like this?
```
   dotspacemacs-configuration-layers
   `(
    (spacemacs-ivy :step pre)
    spacemacs-helm
    ... )
```

**Comment by StreakyCobra** [comment]
@scloudyy Last time I tried, enabling both (maybe with ivy after helm, I don't remember) without additional configuration was enough to have ivy taking the priority over helm.

**Comment by justbur** [comment]
@scloudyy Try it without the pre option. You also want to disable helm-mode, but you have to take into account that helm is deferred.

**Comment by scloudyy** [comment]
@StreakyCobra @justbur 
Partly, in spacemacs-ivy/packages.el, the keybinding in 
```
(defun spacemacs-ivy/init-swiper ()...)
```
```
(defun spacemacs-ivy/init-ivy-spacemacs-help ()...)
```
```
(defun spacemacs-ivy/init-ivy ()...)
```
have overrided helm.Just like 'SPC p l', 'SPC f r ' and 'SPC b b'

But the keybindings in
```
(defun spacemacs-ivy/init-counsel ()...)
```
doesn't work. 
I think maybe it is because the keyinding in *spacemacs-ivy/init-counsel* are all put in the function *spacemacs/describe-mode* and this function is overrided by helm.

```
spacemacs-ivy
```
and
```
(spacemacs-ivy :step pre)
```
is the same.

**Comment by justbur** [comment]
@scloudyy #4750 should fix any trouble with using both. It's going to be hard to configure on the user side before this is merged.

**Comment by scloudyy** [comment]
Great work! Thanks!

**Comment by mkomitee** [comment]
Not sure if this is the right place for this, but the only thing I've noticed that I'm missing using ivy instead of helm is the SPC l b binding to list/search buffers limited to the current layout. It's still configured to use the (unavailable) helm-mini.

**Comment by justbur** [comment]
@mkomitee The layouts stuff is probably the biggest missing item at the moment. I think there's other changes with them coming, so we can maybe add the ivy support at the same time.

**Comment by mkomitee** [comment]
That's reasonable. Thanks for all of your hard work on spacemacs.

**Comment by Andre0991** [comment]
@justbur, I'm testing Ivy and it doesn't show an indicator that I'm using an Ivy session. I opened an issue suggesting that and other things but it turns out that it actually has one, but Spacemacs is now showing it - see the second point in https://github.com/abo-abo/swiper/issues/376 and abo-abo's answer. Is this intentional? I think it'd be nice to have it.

Thanks for the great work with Ivy btw.

**Comment by justbur** [comment]
What do you mean by an ivy session? Are you talking about ivy-mode? Or any
time ivy-read is used?

**Comment by Andre0991** [comment]
Yes, Ivy mode. Sorry, I probably used the wrong term.

 What I mean is that there's no visual indication that the Ivy buffer is an Ivy buffer - use `SPC f f` to check this, for example. But according to @abo-abo , this doesn't happen by default.

**Comment by justbur** [comment]
I think what @abo-abo was referring to is the lighter in the mode-line when ivy-mode is active, which is being hidden [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/spacemacs-ivy/packages.el#L314). As far as I know there's no built-in way to indicate that the buffer is an ivy one. We could change the prompt perhaps, or put something in the mode-line if you like.

**Comment by Andre0991** [comment]
@justbur Ah, right,  I understand what he was referring to now. It's this:

![screenshot 2016-02-03 22 20 34](https://cloud.githubusercontent.com/assets/7083061/12801537/91b28218-cac4-11e5-888e-1869cb08329b.png)


So what I had in mind it's more an upstream issue then. IMO there should be a way for the user to know that he is using an Ivy buffer, like this in Helm:

![screenshot 2016-02-03 22 23 16](https://cloud.githubusercontent.com/assets/7083061/12801565/beacacc6-cac4-11e5-8b6d-b24b6339c44b.png)

@abo-abo :arrow_up: 

So... well, I'd like to see this in `ivy` instead of modifying Spacemacs, but if more people agree that this feature is useful, we could implement it here.

**Comment by justbur** [comment]
@TheBB might be able to do something in spaceline without upstream changes.

**Comment by Andre0991** [comment]
Yes, good idea :+1: 

@justbur, I'm having an issue with `SPC h SPC` and the Ivy layer. Some of my layers don't show up. See:

![screenshot 2016-02-03 23 37 38](https://cloud.githubusercontent.com/assets/7083061/12803129/5961dd86-cacf-11e5-822d-64e61ba6a1ef.png)
 
It happens every time I use `SPC h SPC`.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 18874c9)
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(osx spacemacs-ivy andre-spacemacs-ivy emacs-lisp syntax-checking common-lisp git github
     (shell :variables shell-default-shell 'eshell)
     spacemacs-layouts erc html pdf-tools
     (elfeed :variables rmh-elfeed-org-files
             (list "/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
     themes-megapack semantic
     (auto-completion :variables auto-completion-private-snippets-directory "/Users/andre0991/Dropbox/backup/emacs/yasnippet-snippets/" auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for latex)
     org
     (ranger :variables ranger-show-preview t)
     markdown latex spell-checking version-control mu4e andre-common-lisp andre-elfeed andre-osx andre-erc andre-eww andre-mu4e)
```

**Comment by justbur** [comment]
@Andre0991 `SPC h SPC` uses the same functions to gather package information in the helm and ivy versions. Can you confirm that you have the same problem with helm? This is probably a more general problem.

**Comment by Andre0991** [comment]
@justbur It works with Helm:

![screenshot 2016-02-03 23 52 18](https://cloud.githubusercontent.com/assets/7083061/12803422/3373594a-cad1-11e5-9353-251f98ec3e1b.png)

`andre-eww` is my only personal layer that owns a package. I don't know if this is relevant.

**Comment by justbur** [comment]
> andre-eww is my only personal layer that owns a package. I don't know if this is relevant.

Yep, that's relevant. The default action in `SPC h SPC` is to go to the init function for the package. Try `SPC h l`

**Comment by Andre0991** [comment]
@justbur Ah, right.

Yes, using `spacemacs-ivy`, `SPC h l` shows the other layers too.

**Comment by justbur** [comment]
@Andre0991 #4953

**Comment by Andre0991** [comment]
@justbur Thanks! :+1:

**Comment by AlejandroCatalina** [comment]
Is there any plans to implement `ivy-projectile` or similar? There is an issue with `SPC p h`, it is bound to `helm-projectile`. It shouldn't be bound to it if you have `spacemacs-ivy` enabled, or at least indicate that the corresponding function is yet to be developed. @justbur 

I can work in this issue if it is actually an issue.

**Comment by justbur** [comment]
@AlejandroCatalina I'll add it to the list. I actually just noticed it and removed that binding from the ivy/helm integration pr.

**Comment by AlejandroCatalina** [comment]
Thank you :)

Sent from my Cyanogen phone

On Feb 4, 2016 13:11, Justin Burkett <notifications@github.com> wrote:

@AlejandroCatalina I'll add it to the list. I actually just noticed it and removed that binding from the ivy/helm integration pr.

**Comment by Andre0991** [comment]
@justbur 
I have one more suggestion for the options panel: adding `g` and `G` to execute what `h` and `l` do now and making `h` and `l` scroll up/down n lines, where n is the number of visible lines. 

Rationale: `g` and `G` make more sense in Spacemacs conventions on going to the beginning/end. 
It would be convenient to have`h` and `l` to scroll, and it's like going to the previous/next "pages" as the eww (PR pending) and pdf-tools (PR pending) layers do.

I'd also move `Cancel` to the last column, but that's just a matter of taste.

**Comment by Andre0991** [comment]
Oh, one more thing actually: abo-abo recently added "_D_efinition of this panel", which goes to the definition of the hydra on the code.

I think it'd be nice if we had something similar that provides documentation about the options, especially because our interface differs from the default, but IMO going to the code makes no sense (for this purpose). OK, most of the letters are fairly obvious but it would be useful if the user is not sure about what some of them does.

Perhaps we could use `?` and it would open a file or just pop a window similarly to what `?` in the layouts transient state does.

**Comment by justbur** [comment]
@Andre0991 good suggestions. I made some changes. See what you think. 

> I'd also move Cancel to the last column, but that's just a matter of taste.

It's easier to keep the columns aligned the way I did it, because the toggles are variable width. I can change it, but it doesn't bother be this way.

>  but IMO going to the code makes no sense

The bigger problem is that going to the code won't work in our case, because the hydra is technically defined in a hook. We could write a custom function but it's not worth it I think. 

> Perhaps we could use ? and it would open a file or just pop a window similarly to what ? in the layouts transient state does.

The purpose of that key is to reveal all of the options, not provide documentation. I think the proper place for the explanation is in the docs for spacemacs and not in a second level of popup, but that's just my opinion.

**Comment by Andre0991** [comment]
@justbur 
Yes, I liked `u` and `d`, good solution. I even added those keybindings to the `pdf-tools` to scroll too.

> The purpose of that key is to reveal all of the options, not provide documentation. I think the proper place for the explanation is in the docs for spacemacs and not in a second level of popup, but that's just my opinion.

Yes, good point. Certainly `DOCUMENTATION.org` is the proper place. There could be a key to go to the point referring to the panel in the docs but I don't know if it's worth it. It's convenient but I can't imagine an elegant way of displaying it (see Helm's `C-c ?`, it opens a org file with custom keybindings, it's cumbersome).

**Comment by sooheon** [comment]
I think the ivy config should include `(ido-mode -1)`. Without it, many commands still default to the ido version. For example, `spc a d` comes up in ido, while `M-x dired` uses ivy. Also, there are some commands which use ido even when ido mode is off: `Rollback package update` in the spacemacs buffer does it for sure, and I've encountered some others but can't remember now.

**Comment by justbur** [comment]
Thanks I'll take care of it

**Comment by justbur** [comment]
@sooheon @syl20bnr The rollback button explicitly uses `ido-completing-read` so it's not a matter of `ido-mode` being enabled.

I'm also not really sure why `ido-mode` is enabled in the first place.

**Comment by aaronjensen** [comment]
`SPC i r c` used to open a helm list of irc channels you had set up w/ rcirc, that binding appears to be replaced w/ ivy resume as `SPC i r`.

**Comment by justbur** [comment]
I wasn't crazy about the `ir` binding so it can be moved but I also don't think that irc binding is really consistent with much else and is probably bad for that reason even if it's cute.

**Comment by aaronjensen** [comment]
@justbur yea, i'm good w/ the `irc` binding moving. It was a useful binding. Maybe it could move to a `SPC m` map? ideally it'd be accessible from anywhere, I think.

**Comment by StreakyCobra** [comment]
> [`(spacemacs/set-leader-keys "irc" 'helm-rcirc-auto-join-channels)`](https://github.com/syl20bnr/spacemacs/blob/ba30c06754b6cf13c9674f4863e38af781c56a07/layers/%2Birc/rcirc/packages.el#L33)

That's totally not its place. This should be on `SPC a i` or `SPC m`.

**Comment by aaronjensen** [comment]
'SPC a i i' would be great

**Comment by robbyoconnor** [comment]
I agree -- Let's not break conventions. As is I'm hating the loss of `SPC bd`

**Comment by justbur** [comment]
I just `ivy-resume` on `ri` which I think is just as good. Besides "r" has the "resume" label already.

**Comment by justbur** [comment]
FYI - I think I got all of the perspectives stuff ported in #4969 now

**Comment by justbur** [comment]
Opened a more focused issue at #4999, since the initial work is done IMO. Please direct comments there or to the PR (#4969).
