### ISSUE TITLE
Personal TODO

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#8590]
## My self worth bucket list:
  - **Review my old  tickets and close theme or provide PR:**
    - [x] #7306 *- Fix go and ctags key binding conflict*
      - PR #8522 
        - [x] **merge me** :shipit:
    - [x] #8608 ~*- add focus-mode tool*~ (too glitchy)
    - [x] #7186 *- Replace github-browse-file with browse-at-remote ?* 
      - PR #8601 
        - [x] **merge me** :shipit:
    - [x] #7185 *- add bm.el tool (Visible bookmarks)* 
      - PR #8598
        - [x] **merge me** :shipit:
    - [x] #7170 *- Add fireplace.el layer* 
      - seems unmaintained.
    - [x] #7169 *- Spacemacsify zone.el* 
      - PR #8602
        - [x] **merge me** :shipit:
    - [x] #7168 #2776 *- Add impatient-mode to the html layer*
    - [ ] #7159 *- add gorepl-mode.el (A minor emacs mode for Go REPL)* 
    - [x] #7156 *- add symon.el tool (tiny graphical system monitor)* 
      - PR #8595
        - [x] **merge me** :shipit:
    - [ ] #5996 *- Add natural languages layer* 
    - [ ] #6505 *- Add ergonomics enforcers layer* 
    - [x] #7001 *- Spacemacs torrent client*
      - PR #7053
        - [x] **merge me** :shipit:
    - [x] #7675 *- `spacefmt` should properly handle trees*
      - PR #8594
        - [x] **merge me** :shipit:
    - [x] #8593 *-  fix: `spacefmt` hang on tables without a header*
      - PR #8594
        - [x] **merge me** :shipit:
    - [ ] #8520 #8521 *- Detect Spacemacs key binding collisions(CI)*
  - **Make centered buffer mode more useful:**
    - [x] #7394 *- Centered buffer mode not working as expected...* - added for reference
    - [x] #247 *- Distraction free mode/centered buffer in Spacemacs?*
    - [x] #3934 *- it's about the previous implementation*  **(close the issue?)**
    - [x] #7421 *- centered-buffer-mode is much less useful since 0.200*
    - [x] #7857 *- Centered buffer mode doesn't work*
  - **PR without an issue (MERGE):**
    - [x] #8588 *- Redesign spacemacs-docker distribution*
        - [x] **merge me** :shipit:
    - [x] #8606 *- colorized output for CI space-test*
        - [x] **merge me** :shipit:

**Comment by JAremko** [comment]
I'll think about making it into April Challenge :smile:

**Comment by robbyoconnor** [comment]
Spring cleaning?

**Comment by JAremko** [comment]
@robbyoconnor Kinda, but more like cleansing :dagger:\ :shipit:/:hocho:

**Comment by robbyoconnor** [comment]
LOLLL
